modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="pineapplemod"
version="1.1.0"
displayName="PineappleMod"
credits="Inspired by @alexanderdude13 and @gracegorgeous11"
displayURL="https://github.com/alicraigmile/pineapplemod"
authors="Ali Craigmile"
description='''
All things pineapple
'''

[[dependencies.pineapplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




