modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="pineapplemod"
version="1.0.0"
displayName="PineappleMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://kaimoriginals.com/minecraft"
authors="Ali Craigmile"
description='''
Everything pineapple
'''

[[dependencies.pineapplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




